/******************************************************************************
 * File Name   : MX_Device.h
 * Date        : 01/09/2024 22:11:12
 * Description : STM32Cube MX parameter definitions
 * Note        : This file is generated by STM32CubeMX (DO NOT EDIT!)
 ******************************************************************************/

#ifndef __MX_DEVICE_H
#define __MX_DEVICE_H

/*---------------------------- Clock Configuration ---------------------------*/

#define MX_LSI_VALUE                            32000
#define MX_LSE_VALUE                            32768
#define MX_HSI_VALUE                            64000000
#define MX_HSE_VALUE                            25000000
#define MX_EXTERNAL_CLOCK_VALUE                 12288000
#define MX_PLLDSIFreq_Value                     500000000
#define MX_SYSCLKFreq_VALUE                     480000000
#define MX_HCLKFreq_Value                       240000000
#define MX_CortexFreq_Value                     480000000
#define MX_APB1Freq_Value                       120000000
#define MX_APB2Freq_Value                       120000000
#define MX_CECFreq_Value                        32000
#define MX_RTCFreq_Value                        32000
#define MX_USBFreq_Value                        480000000
#define MX_WatchDogFreq_Value                   32000
#define MX_DSIFreq_Value                        96000000
#define MX_DSIPHYCLKFreq_Value                  96000000
#define MX_DSITXEscFreq_Value                   20000000
#define MX_SPDIFRXFreq_Value                    480000000
#define MX_MCO1PinFreq_Value                    64000000
#define MX_MCO2PinFreq_Value                    480000000

/*-------------------------------- BDMA       --------------------------------*/

#define MX_BDMA                                 1

/* NVIC Configuration */

/* NVIC BDMA_Channel1_IRQn */
#define MX_BDMA_Channel1_IRQn_interruptPremptionPriority 0
#define MX_BDMA_Channel1_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_BDMA_Channel1_IRQn_Subriority        0

/* NVIC BDMA_Channel0_IRQn */
#define MX_BDMA_Channel0_IRQn_interruptPremptionPriority 0
#define MX_BDMA_Channel0_IRQn_PriorityGroup     NVIC_PRIORITYGROUP_4
#define MX_BDMA_Channel0_IRQn_Subriority        0

/*-------------------------------- CORTEX_M7  --------------------------------*/

#define MX_CORTEX_M7                            1

/* GPIO Configuration */

/*-------------------------------- DEBUG      --------------------------------*/

#define MX_DEBUG                                1

/* GPIO Configuration */

/* Pin PA14 (JTCK/SWCLK) */
#define MX_DEBUG_JTCK_SWCLK_Pin                 PA14_JTCK_SWCLK
#define MX_DEBUG_JTCK_SWCLK_PinAttribute        Free

/* Pin PB3 (JTDO/TRACESWO) */
#define MX_DEBUG_JTDO_SWO_Pin                   PB3_JTDO_TRACESWO
#define MX_DEBUG_JTDO_SWO_PinAttribute          Free

/* Pin PA13 (JTMS/SWDIO) */
#define MX_DEBUG_JTMS_SWDIO_Pin                 PA13_JTMS_SWDIO
#define MX_DEBUG_JTMS_SWDIO_PinAttribute        Free

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA2_Stream2_IRQn */
#define MX_DMA2_Stream2_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream2_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream2_IRQn_Subriority         0

/* NVIC DMA1_Stream6_IRQn */
#define MX_DMA1_Stream6_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream6_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream6_IRQn_Subriority         0

/* NVIC DMA1_Stream2_IRQn */
#define MX_DMA1_Stream2_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream2_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream2_IRQn_Subriority         0

/* NVIC DMA2_Stream3_IRQn */
#define MX_DMA2_Stream3_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream3_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream3_IRQn_Subriority         0

/* NVIC DMA2_Stream0_IRQn */
#define MX_DMA2_Stream0_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream0_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream0_IRQn_Subriority         0

/* NVIC DMA1_Stream5_IRQn */
#define MX_DMA1_Stream5_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream5_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream5_IRQn_Subriority         0

/* NVIC DMA1_Stream3_IRQn */
#define MX_DMA1_Stream3_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream3_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream3_IRQn_Subriority         0

/* NVIC DMA1_Stream0_IRQn */
#define MX_DMA1_Stream0_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream0_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream0_IRQn_Subriority         0

/* NVIC DMA2_Stream5_IRQn */
#define MX_DMA2_Stream5_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream5_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream5_IRQn_Subriority         0

/* NVIC DMA1_Stream4_IRQn */
#define MX_DMA1_Stream4_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream4_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream4_IRQn_Subriority         0

/* NVIC DMA1_Stream7_IRQn */
#define MX_DMA1_Stream7_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream7_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream7_IRQn_Subriority         0

/* NVIC DMA1_Stream1_IRQn */
#define MX_DMA1_Stream1_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream1_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream1_IRQn_Subriority         0

/* NVIC DMA2_Stream4_IRQn */
#define MX_DMA2_Stream4_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream4_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream4_IRQn_Subriority         0

/* NVIC DMA2_Stream7_IRQn */
#define MX_DMA2_Stream7_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream7_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream7_IRQn_Subriority         0

/* NVIC DMA2_Stream6_IRQn */
#define MX_DMA2_Stream6_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream6_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream6_IRQn_Subriority         0

/* NVIC DMA2_Stream1_IRQn */
#define MX_DMA2_Stream1_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream1_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream1_IRQn_Subriority         0

/*-------------------------------- DMA        --------------------------------*/

#define MX_DMA                                  1

/* NVIC Configuration */

/* NVIC DMA2_Stream2_IRQn */
#define MX_DMA2_Stream2_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream2_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream2_IRQn_Subriority         0

/* NVIC DMA1_Stream6_IRQn */
#define MX_DMA1_Stream6_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream6_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream6_IRQn_Subriority         0

/* NVIC DMA1_Stream2_IRQn */
#define MX_DMA1_Stream2_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream2_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream2_IRQn_Subriority         0

/* NVIC DMA2_Stream3_IRQn */
#define MX_DMA2_Stream3_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream3_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream3_IRQn_Subriority         0

/* NVIC DMA2_Stream0_IRQn */
#define MX_DMA2_Stream0_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream0_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream0_IRQn_Subriority         0

/* NVIC DMA1_Stream5_IRQn */
#define MX_DMA1_Stream5_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream5_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream5_IRQn_Subriority         0

/* NVIC DMA1_Stream3_IRQn */
#define MX_DMA1_Stream3_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream3_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream3_IRQn_Subriority         0

/* NVIC DMA1_Stream0_IRQn */
#define MX_DMA1_Stream0_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream0_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream0_IRQn_Subriority         0

/* NVIC DMA2_Stream5_IRQn */
#define MX_DMA2_Stream5_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream5_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream5_IRQn_Subriority         0

/* NVIC DMA1_Stream4_IRQn */
#define MX_DMA1_Stream4_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream4_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream4_IRQn_Subriority         0

/* NVIC DMA1_Stream7_IRQn */
#define MX_DMA1_Stream7_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream7_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream7_IRQn_Subriority         0

/* NVIC DMA1_Stream1_IRQn */
#define MX_DMA1_Stream1_IRQn_interruptPremptionPriority 0
#define MX_DMA1_Stream1_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA1_Stream1_IRQn_Subriority         0

/* NVIC DMA2_Stream4_IRQn */
#define MX_DMA2_Stream4_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream4_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream4_IRQn_Subriority         0

/* NVIC DMA2_Stream7_IRQn */
#define MX_DMA2_Stream7_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream7_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream7_IRQn_Subriority         0

/* NVIC DMA2_Stream6_IRQn */
#define MX_DMA2_Stream6_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream6_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream6_IRQn_Subriority         0

/* NVIC DMA2_Stream1_IRQn */
#define MX_DMA2_Stream1_IRQn_interruptPremptionPriority 0
#define MX_DMA2_Stream1_IRQn_PriorityGroup      NVIC_PRIORITYGROUP_4
#define MX_DMA2_Stream1_IRQn_Subriority         0

/*-------------------------------- ETH        --------------------------------*/

#define MX_ETH                                  1

/* GPIO Configuration */

/* Pin PA1 */
#define MX_ETH_REF_CLK_GPIO_Speed               GPIO_SPEED_FREQ_LOW
#define MX_ETH_REF_CLK_Pin                      PA1
#define MX_ETH_REF_CLK_GPIOx                    GPIOA
#define MX_ETH_REF_CLK_GPIO_PuPd                GPIO_NOPULL
#define MX_ETH_REF_CLK_GPIO_Pin                 GPIO_PIN_1
#define MX_ETH_REF_CLK_GPIO_AF                  GPIO_AF11_ETH
#define MX_ETH_REF_CLK_GPIO_Mode                GPIO_MODE_AF_PP
#define MX_ETH_REF_CLK_PinAttribute             Free

/* Pin PA7 */
#define MX_ETH_CRS_DV_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_ETH_CRS_DV_Pin                       PA7
#define MX_ETH_CRS_DV_GPIOx                     GPIOA
#define MX_ETH_CRS_DV_GPIO_PuPd                 GPIO_NOPULL
#define MX_ETH_CRS_DV_GPIO_Pin                  GPIO_PIN_7
#define MX_ETH_CRS_DV_GPIO_AF                   GPIO_AF11_ETH
#define MX_ETH_CRS_DV_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_ETH_CRS_DV_PinAttribute              Free

/* Pin PC4 */
#define MX_ETH_RXD0_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_RXD0_Pin                         PC4
#define MX_ETH_RXD0_GPIOx                       GPIOC
#define MX_ETH_RXD0_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_RXD0_GPIO_Pin                    GPIO_PIN_4
#define MX_ETH_RXD0_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD0_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_ETH_RXD0_PinAttribute                Free

/* Pin PC5 */
#define MX_ETH_RXD1_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_RXD1_Pin                         PC5
#define MX_ETH_RXD1_GPIOx                       GPIOC
#define MX_ETH_RXD1_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_RXD1_GPIO_Pin                    GPIO_PIN_5
#define MX_ETH_RXD1_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_RXD1_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_ETH_RXD1_PinAttribute                Free

/* Pin PG11 */
#define MX_ETH_TX_EN_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_ETH_TX_EN_Pin                        PG11
#define MX_ETH_TX_EN_GPIOx                      GPIOG
#define MX_ETH_TX_EN_GPIO_PuPd                  GPIO_NOPULL
#define MX_ETH_TX_EN_GPIO_Pin                   GPIO_PIN_11
#define MX_ETH_TX_EN_GPIO_AF                    GPIO_AF11_ETH
#define MX_ETH_TX_EN_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_ETH_TX_EN_PinAttribute               Free

/* Pin PA2 */
#define MX_ETH_MDIO_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_MDIO_Pin                         PA2
#define MX_ETH_MDIO_GPIOx                       GPIOA
#define MX_ETH_MDIO_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_MDIO_GPIO_Pin                    GPIO_PIN_2
#define MX_ETH_MDIO_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_MDIO_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_ETH_MDIO_PinAttribute                Free

/* Pin PG12 */
#define MX_ETH_TXD1_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_TXD1_Pin                         PG12
#define MX_ETH_TXD1_GPIOx                       GPIOG
#define MX_ETH_TXD1_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_TXD1_GPIO_Pin                    GPIO_PIN_12
#define MX_ETH_TXD1_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD1_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_ETH_TXD1_PinAttribute                Free

/* Pin PG13 */
#define MX_ETH_TXD0_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_ETH_TXD0_Pin                         PG13
#define MX_ETH_TXD0_GPIOx                       GPIOG
#define MX_ETH_TXD0_GPIO_PuPd                   GPIO_NOPULL
#define MX_ETH_TXD0_GPIO_Pin                    GPIO_PIN_13
#define MX_ETH_TXD0_GPIO_AF                     GPIO_AF11_ETH
#define MX_ETH_TXD0_GPIO_Mode                   GPIO_MODE_AF_PP

/* Pin PC1 */
#define MX_ETH_MDC_GPIO_Speed                   GPIO_SPEED_FREQ_LOW
#define MX_ETH_MDC_Pin                          PC1
#define MX_ETH_MDC_GPIOx                        GPIOC
#define MX_ETH_MDC_GPIO_PuPd                    GPIO_NOPULL
#define MX_ETH_MDC_GPIO_Pin                     GPIO_PIN_1
#define MX_ETH_MDC_GPIO_AF                      GPIO_AF11_ETH
#define MX_ETH_MDC_GPIO_Mode                    GPIO_MODE_AF_PP
#define MX_ETH_MDC_PinAttribute                 Free

/* NVIC Configuration */

/* NVIC ETH_IRQn */
#define MX_ETH_IRQn_interruptPremptionPriority  0
#define MX_ETH_IRQn_PriorityGroup               NVIC_PRIORITYGROUP_4
#define MX_ETH_IRQn_Subriority                  0

/*-------------------------------- FDCAN1     --------------------------------*/

#define MX_FDCAN1                               1

/* GPIO Configuration */

/* Pin PH13 */
#define MX_FDCAN1_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_FDCAN1_TX_Pin                        PH13
#define MX_FDCAN1_TX_GPIOx                      GPIOH
#define MX_FDCAN1_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_FDCAN1_TX_GPIO_Pin                   GPIO_PIN_13
#define MX_FDCAN1_TX_GPIO_AF                    GPIO_AF9_FDCAN1
#define MX_FDCAN1_TX_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_FDCAN1_TX_PinAttribute               Free

/* Pin PH14 */
#define MX_FDCAN1_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_FDCAN1_RX_Pin                        PH14
#define MX_FDCAN1_RX_GPIOx                      GPIOH
#define MX_FDCAN1_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_FDCAN1_RX_GPIO_Pin                   GPIO_PIN_14
#define MX_FDCAN1_RX_GPIO_AF                    GPIO_AF9_FDCAN1
#define MX_FDCAN1_RX_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_FDCAN1_RX_PinAttribute               Free

/* NVIC Configuration */

/* NVIC FDCAN1_IT1_IRQn */
#define MX_FDCAN1_IT1_IRQn_interruptPremptionPriority 0
#define MX_FDCAN1_IT1_IRQn_PriorityGroup        NVIC_PRIORITYGROUP_4
#define MX_FDCAN1_IT1_IRQn_Subriority           0

/* NVIC FDCAN1_IT0_IRQn */
#define MX_FDCAN1_IT0_IRQn_interruptPremptionPriority 0
#define MX_FDCAN1_IT0_IRQn_PriorityGroup        NVIC_PRIORITYGROUP_4
#define MX_FDCAN1_IT0_IRQn_Subriority           0

/*-------------------------------- FDCAN2     --------------------------------*/

#define MX_FDCAN2                               1

/* GPIO Configuration */

/* Pin PB12 */
#define MX_FDCAN2_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_FDCAN2_RX_Pin                        PB12
#define MX_FDCAN2_RX_GPIOx                      GPIOB
#define MX_FDCAN2_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_FDCAN2_RX_GPIO_Pin                   GPIO_PIN_12
#define MX_FDCAN2_RX_GPIO_AF                    GPIO_AF9_FDCAN2
#define MX_FDCAN2_RX_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_FDCAN2_RX_PinAttribute               Free

/* Pin PB6 */
#define MX_FDCAN2_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_FDCAN2_TX_GPIO_FM6                   __NULL
#define MX_FDCAN2_TX_Pin                        PB6
#define MX_FDCAN2_TX_GPIOx                      GPIOB
#define MX_FDCAN2_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_FDCAN2_TX_GPIO_Pin                   GPIO_PIN_6
#define MX_FDCAN2_TX_GPIO_AF                    GPIO_AF9_FDCAN2
#define MX_FDCAN2_TX_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_FDCAN2_TX_PinAttribute               Free

/* NVIC Configuration */

/* NVIC FDCAN2_IT1_IRQn */
#define MX_FDCAN2_IT1_IRQn_interruptPremptionPriority 0
#define MX_FDCAN2_IT1_IRQn_PriorityGroup        NVIC_PRIORITYGROUP_4
#define MX_FDCAN2_IT1_IRQn_Subriority           0

/* NVIC FDCAN2_IT0_IRQn */
#define MX_FDCAN2_IT0_IRQn_interruptPremptionPriority 0
#define MX_FDCAN2_IT0_IRQn_PriorityGroup        NVIC_PRIORITYGROUP_4
#define MX_FDCAN2_IT0_IRQn_Subriority           0

/*-------------------------------- FMC        --------------------------------*/

#define MX_FMC                                  1

/* GPIO Configuration */

/* Pin PE11 */
#define MX_FMC_D8_DA8_Pin                       PE11
#define MX_FMC_D8_DA8_GPIOx                     GPIOE
#define MX_FMC_D8_DA8_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D8_DA8_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D8_DA8_GPIO_Pin                  GPIO_PIN_11
#define MX_FMC_D8_DA8_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D8_DA8_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_FMC_D8_DA8_PinAttribute              Free

/* Pin PH7 */
#define MX_FMC_SDCKE1_Pin                       PH7
#define MX_FMC_SDCKE1_GPIOx                     GPIOH
#define MX_FMC_SDCKE1_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_SDCKE1_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_SDCKE1_GPIO_Pin                  GPIO_PIN_7
#define MX_FMC_SDCKE1_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_SDCKE1_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_FMC_SDCKE1_PinAttribute              Free

/* Pin PF0 */
#define MX_FMC_A0_Pin                           PF0
#define MX_FMC_A0_GPIOx                         GPIOF
#define MX_FMC_A0_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A0_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A0_GPIO_Pin                      GPIO_PIN_0
#define MX_FMC_A0_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A0_GPIO_Mode                     GPIO_MODE_AF_PP
#define MX_FMC_A0_PinAttribute                  Free

/* Pin PF1 */
#define MX_FMC_A1_Pin                           PF1
#define MX_FMC_A1_GPIOx                         GPIOF
#define MX_FMC_A1_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A1_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A1_GPIO_Pin                      GPIO_PIN_1
#define MX_FMC_A1_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A1_GPIO_Mode                     GPIO_MODE_AF_PP
#define MX_FMC_A1_PinAttribute                  Free

/* Pin PD1 */
#define MX_FMC_D3_DA3_Pin                       PD1
#define MX_FMC_D3_DA3_GPIOx                     GPIOD
#define MX_FMC_D3_DA3_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D3_DA3_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D3_DA3_GPIO_Pin                  GPIO_PIN_1
#define MX_FMC_D3_DA3_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D3_DA3_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_FMC_D3_DA3_PinAttribute              Free

/* Pin PF2 */
#define MX_FMC_A2_Pin                           PF2
#define MX_FMC_A2_GPIOx                         GPIOF
#define MX_FMC_A2_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A2_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A2_GPIO_Pin                      GPIO_PIN_2
#define MX_FMC_A2_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A2_GPIO_Mode                     GPIO_MODE_AF_PP
#define MX_FMC_A2_PinAttribute                  Free

/* Pin PF11 */
#define MX_FMC_SDNRAS_Pin                       PF11
#define MX_FMC_SDNRAS_GPIOx                     GPIOF
#define MX_FMC_SDNRAS_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_SDNRAS_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_SDNRAS_GPIO_Pin                  GPIO_PIN_11
#define MX_FMC_SDNRAS_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_SDNRAS_GPIO_Mode                 GPIO_MODE_AF_PP

/* Pin PF3 */
#define MX_FMC_A3_Pin                           PF3
#define MX_FMC_A3_GPIOx                         GPIOF
#define MX_FMC_A3_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A3_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A3_GPIO_Pin                      GPIO_PIN_3
#define MX_FMC_A3_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A3_GPIO_Mode                     GPIO_MODE_AF_PP
#define MX_FMC_A3_PinAttribute                  Free

/* Pin PF4 */
#define MX_FMC_A4_Pin                           PF4
#define MX_FMC_A4_GPIOx                         GPIOF
#define MX_FMC_A4_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A4_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A4_GPIO_Pin                      GPIO_PIN_4
#define MX_FMC_A4_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A4_GPIO_Mode                     GPIO_MODE_AF_PP
#define MX_FMC_A4_PinAttribute                  Free

/* Pin PH6 */
#define MX_FMC_SDNE1_Pin                        PH6
#define MX_FMC_SDNE1_GPIOx                      GPIOH
#define MX_FMC_SDNE1_GPIO_PuPd                  GPIO_NOPULL
#define MX_FMC_SDNE1_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_SDNE1_GPIO_Pin                   GPIO_PIN_6
#define MX_FMC_SDNE1_GPIO_AF                    GPIO_AF12_FMC
#define MX_FMC_SDNE1_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_FMC_SDNE1_PinAttribute               Free

/* Pin PF5 */
#define MX_FMC_A5_Pin                           PF5
#define MX_FMC_A5_GPIOx                         GPIOF
#define MX_FMC_A5_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A5_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A5_GPIO_Pin                      GPIO_PIN_5
#define MX_FMC_A5_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A5_GPIO_Mode                     GPIO_MODE_AF_PP
#define MX_FMC_A5_PinAttribute                  Free

/* Pin PC0 */
#define MX_FMC_SDNWE_Pin                        PC0
#define MX_FMC_SDNWE_GPIOx                      GPIOC
#define MX_FMC_SDNWE_GPIO_PuPd                  GPIO_NOPULL
#define MX_FMC_SDNWE_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_SDNWE_GPIO_Pin                   GPIO_PIN_0
#define MX_FMC_SDNWE_GPIO_AF                    GPIO_AF12_FMC
#define MX_FMC_SDNWE_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_FMC_SDNWE_PinAttribute               Free

/* Pin PF12 */
#define MX_FMC_A6_Pin                           PF12
#define MX_FMC_A6_GPIOx                         GPIOF
#define MX_FMC_A6_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A6_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A6_GPIO_Pin                      GPIO_PIN_12
#define MX_FMC_A6_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A6_GPIO_Mode                     GPIO_MODE_AF_PP
#define MX_FMC_A6_PinAttribute                  Free

/* Pin PG0 */
#define MX_FMC_A10_Pin                          PG0
#define MX_FMC_A10_GPIOx                        GPIOG
#define MX_FMC_A10_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_A10_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A10_GPIO_Pin                     GPIO_PIN_0
#define MX_FMC_A10_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_A10_GPIO_Mode                    GPIO_MODE_AF_PP
#define MX_FMC_A10_PinAttribute                 Free

/* Pin PF13 */
#define MX_FMC_A7_Pin                           PF13
#define MX_FMC_A7_GPIOx                         GPIOF
#define MX_FMC_A7_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A7_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A7_GPIO_Pin                      GPIO_PIN_13
#define MX_FMC_A7_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A7_GPIO_Mode                     GPIO_MODE_AF_PP
#define MX_FMC_A7_PinAttribute                  Free

/* Pin PD9 */
#define MX_FMC_D14_DA14_Pin                     PD9
#define MX_FMC_D14_DA14_GPIOx                   GPIOD
#define MX_FMC_D14_DA14_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D14_DA14_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D14_DA14_GPIO_Pin                GPIO_PIN_9
#define MX_FMC_D14_DA14_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D14_DA14_GPIO_Mode               GPIO_MODE_AF_PP
#define MX_FMC_D14_DA14_PinAttribute            Free

/* Pin PF14 */
#define MX_FMC_A8_Pin                           PF14
#define MX_FMC_A8_GPIOx                         GPIOF
#define MX_FMC_A8_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A8_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A8_GPIO_Pin                      GPIO_PIN_14
#define MX_FMC_A8_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A8_GPIO_Mode                     GPIO_MODE_AF_PP
#define MX_FMC_A8_PinAttribute                  Free

/* Pin PF15 */
#define MX_FMC_A9_Pin                           PF15
#define MX_FMC_A9_GPIOx                         GPIOF
#define MX_FMC_A9_GPIO_PuPd                     GPIO_NOPULL
#define MX_FMC_A9_GPIO_Speed_High_Default       GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A9_GPIO_Pin                      GPIO_PIN_15
#define MX_FMC_A9_GPIO_AF                       GPIO_AF12_FMC
#define MX_FMC_A9_GPIO_Mode                     GPIO_MODE_AF_PP
#define MX_FMC_A9_PinAttribute                  Free

/* Pin PG1 */
#define MX_FMC_A11_Pin                          PG1
#define MX_FMC_A11_GPIOx                        GPIOG
#define MX_FMC_A11_GPIO_PuPd                    GPIO_NOPULL
#define MX_FMC_A11_GPIO_Speed_High_Default      GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A11_GPIO_Pin                     GPIO_PIN_1
#define MX_FMC_A11_GPIO_AF                      GPIO_AF12_FMC
#define MX_FMC_A11_GPIO_Mode                    GPIO_MODE_AF_PP
#define MX_FMC_A11_PinAttribute                 Free

/* Pin PE14 */
#define MX_FMC_D11_DA11_Pin                     PE14
#define MX_FMC_D11_DA11_GPIOx                   GPIOE
#define MX_FMC_D11_DA11_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D11_DA11_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D11_DA11_GPIO_Pin                GPIO_PIN_14
#define MX_FMC_D11_DA11_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D11_DA11_GPIO_Mode               GPIO_MODE_AF_PP
#define MX_FMC_D11_DA11_PinAttribute            Free

/* Pin PE7 */
#define MX_FMC_D4_DA4_Pin                       PE7
#define MX_FMC_D4_DA4_GPIOx                     GPIOE
#define MX_FMC_D4_DA4_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D4_DA4_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D4_DA4_GPIO_Pin                  GPIO_PIN_7
#define MX_FMC_D4_DA4_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D4_DA4_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_FMC_D4_DA4_PinAttribute              Free

/* Pin PE10 */
#define MX_FMC_D7_DA7_Pin                       PE10
#define MX_FMC_D7_DA7_GPIOx                     GPIOE
#define MX_FMC_D7_DA7_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D7_DA7_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D7_DA7_GPIO_Pin                  GPIO_PIN_10
#define MX_FMC_D7_DA7_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D7_DA7_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_FMC_D7_DA7_PinAttribute              Free

/* Pin PG5 */
#define MX_FMC_A15_BA1_Pin                      PG5
#define MX_FMC_A15_BA1_GPIOx                    GPIOG
#define MX_FMC_A15_BA1_GPIO_PuPd                GPIO_NOPULL
#define MX_FMC_A15_BA1_GPIO_Speed_High_Default  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A15_BA1_GPIO_Pin                 GPIO_PIN_5
#define MX_FMC_A15_BA1_GPIO_AF                  GPIO_AF12_FMC
#define MX_FMC_A15_BA1_GPIO_Mode                GPIO_MODE_AF_PP
#define MX_FMC_A15_BA1_PinAttribute             Free

/* Pin PE1 */
#define MX_FMC_NBL1_Pin                         PE1
#define MX_FMC_NBL1_GPIOx                       GPIOE
#define MX_FMC_NBL1_GPIO_PuPd                   GPIO_NOPULL
#define MX_FMC_NBL1_GPIO_Speed_High_Default     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NBL1_GPIO_Pin                    GPIO_PIN_1
#define MX_FMC_NBL1_GPIO_AF                     GPIO_AF12_FMC
#define MX_FMC_NBL1_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_FMC_NBL1_PinAttribute                Free

/* Pin PE0 */
#define MX_FMC_NBL0_Pin                         PE0
#define MX_FMC_NBL0_GPIOx                       GPIOE
#define MX_FMC_NBL0_GPIO_PuPd                   GPIO_NOPULL
#define MX_FMC_NBL0_GPIO_Speed_High_Default     GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_NBL0_GPIO_Pin                    GPIO_PIN_0
#define MX_FMC_NBL0_GPIO_AF                     GPIO_AF12_FMC
#define MX_FMC_NBL0_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_FMC_NBL0_PinAttribute                Free

/* Pin PD14 */
#define MX_FMC_D0_DA0_Pin                       PD14
#define MX_FMC_D0_DA0_GPIOx                     GPIOD
#define MX_FMC_D0_DA0_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D0_DA0_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D0_DA0_GPIO_Pin                  GPIO_PIN_14
#define MX_FMC_D0_DA0_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D0_DA0_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_FMC_D0_DA0_PinAttribute              Free

/* Pin PE8 */
#define MX_FMC_D5_DA5_Pin                       PE8
#define MX_FMC_D5_DA5_GPIOx                     GPIOE
#define MX_FMC_D5_DA5_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D5_DA5_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D5_DA5_GPIO_Pin                  GPIO_PIN_8
#define MX_FMC_D5_DA5_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D5_DA5_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_FMC_D5_DA5_PinAttribute              Free

/* Pin PE13 */
#define MX_FMC_D10_DA10_Pin                     PE13
#define MX_FMC_D10_DA10_GPIOx                   GPIOE
#define MX_FMC_D10_DA10_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D10_DA10_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D10_DA10_GPIO_Pin                GPIO_PIN_13
#define MX_FMC_D10_DA10_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D10_DA10_GPIO_Mode               GPIO_MODE_AF_PP
#define MX_FMC_D10_DA10_PinAttribute            Free

/* Pin PD8 */
#define MX_FMC_D13_DA13_Pin                     PD8
#define MX_FMC_D13_DA13_GPIOx                   GPIOD
#define MX_FMC_D13_DA13_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D13_DA13_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D13_DA13_GPIO_Pin                GPIO_PIN_8
#define MX_FMC_D13_DA13_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D13_DA13_GPIO_Mode               GPIO_MODE_AF_PP
#define MX_FMC_D13_DA13_PinAttribute            Free

/* Pin PG4 */
#define MX_FMC_A14_BA0_Pin                      PG4
#define MX_FMC_A14_BA0_GPIOx                    GPIOG
#define MX_FMC_A14_BA0_GPIO_PuPd                GPIO_NOPULL
#define MX_FMC_A14_BA0_GPIO_Speed_High_Default  GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_A14_BA0_GPIO_Pin                 GPIO_PIN_4
#define MX_FMC_A14_BA0_GPIO_AF                  GPIO_AF12_FMC
#define MX_FMC_A14_BA0_GPIO_Mode                GPIO_MODE_AF_PP
#define MX_FMC_A14_BA0_PinAttribute             Free

/* Pin PG8 */
#define MX_FMC_SDCLK_Pin                        PG8
#define MX_FMC_SDCLK_GPIOx                      GPIOG
#define MX_FMC_SDCLK_GPIO_PuPd                  GPIO_NOPULL
#define MX_FMC_SDCLK_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_SDCLK_GPIO_Pin                   GPIO_PIN_8
#define MX_FMC_SDCLK_GPIO_AF                    GPIO_AF12_FMC
#define MX_FMC_SDCLK_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_FMC_SDCLK_PinAttribute               Free

/* Pin PE15 */
#define MX_FMC_D12_DA12_Pin                     PE15
#define MX_FMC_D12_DA12_GPIOx                   GPIOE
#define MX_FMC_D12_DA12_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D12_DA12_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D12_DA12_GPIO_Pin                GPIO_PIN_15
#define MX_FMC_D12_DA12_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D12_DA12_GPIO_Mode               GPIO_MODE_AF_PP
#define MX_FMC_D12_DA12_PinAttribute            Free

/* Pin PD15 */
#define MX_FMC_D1_DA1_Pin                       PD15
#define MX_FMC_D1_DA1_GPIOx                     GPIOD
#define MX_FMC_D1_DA1_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D1_DA1_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D1_DA1_GPIO_Pin                  GPIO_PIN_15
#define MX_FMC_D1_DA1_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D1_DA1_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_FMC_D1_DA1_PinAttribute              Free

/* Pin PG15 */
#define MX_FMC_SDNCAS_Pin                       PG15
#define MX_FMC_SDNCAS_GPIOx                     GPIOG
#define MX_FMC_SDNCAS_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_SDNCAS_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_SDNCAS_GPIO_Pin                  GPIO_PIN_15
#define MX_FMC_SDNCAS_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_SDNCAS_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_FMC_SDNCAS_PinAttribute              Free

/* Pin PE12 */
#define MX_FMC_D9_DA9_Pin                       PE12
#define MX_FMC_D9_DA9_GPIOx                     GPIOE
#define MX_FMC_D9_DA9_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D9_DA9_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D9_DA9_GPIO_Pin                  GPIO_PIN_12
#define MX_FMC_D9_DA9_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D9_DA9_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_FMC_D9_DA9_PinAttribute              Free

/* Pin PD0 */
#define MX_FMC_D2_DA2_Pin                       PD0
#define MX_FMC_D2_DA2_GPIOx                     GPIOD
#define MX_FMC_D2_DA2_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D2_DA2_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D2_DA2_GPIO_Pin                  GPIO_PIN_0
#define MX_FMC_D2_DA2_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D2_DA2_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_FMC_D2_DA2_PinAttribute              Free

/* Pin PE9 */
#define MX_FMC_D6_DA6_Pin                       PE9
#define MX_FMC_D6_DA6_GPIOx                     GPIOE
#define MX_FMC_D6_DA6_GPIO_PuPd                 GPIO_NOPULL
#define MX_FMC_D6_DA6_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D6_DA6_GPIO_Pin                  GPIO_PIN_9
#define MX_FMC_D6_DA6_GPIO_AF                   GPIO_AF12_FMC
#define MX_FMC_D6_DA6_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_FMC_D6_DA6_PinAttribute              Free

/* Pin PD10 */
#define MX_FMC_D15_DA15_Pin                     PD10
#define MX_FMC_D15_DA15_GPIOx                   GPIOD
#define MX_FMC_D15_DA15_GPIO_PuPd               GPIO_NOPULL
#define MX_FMC_D15_DA15_GPIO_Speed_High_Default GPIO_SPEED_FREQ_VERY_HIGH
#define MX_FMC_D15_DA15_GPIO_Pin                GPIO_PIN_10
#define MX_FMC_D15_DA15_GPIO_AF                 GPIO_AF12_FMC
#define MX_FMC_D15_DA15_GPIO_Mode               GPIO_MODE_AF_PP
#define MX_FMC_D15_DA15_PinAttribute            Free

/*-------------------------------- I2C2       --------------------------------*/

#define MX_I2C2                                 1

/* GPIO Configuration */

/* Pin PH5 */
#define MX_I2C2_SDA_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_I2C2_SDA_Pin                         PH5
#define MX_I2C2_SDA_GPIOx                       GPIOH
#define MX_I2C2_SDA_GPIO_Pin                    GPIO_PIN_5
#define MX_I2C2_SDA_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SDA_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C2_SDA_GPIO_Mode                   GPIO_MODE_AF_OD
#define MX_I2C2_SDA_PinAttribute                Free

/* Pin PH4 */
#define MX_I2C2_SCL_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_I2C2_SCL_Pin                         PH4
#define MX_I2C2_SCL_GPIOx                       GPIOH
#define MX_I2C2_SCL_GPIO_Pin                    GPIO_PIN_4
#define MX_I2C2_SCL_GPIO_AF                     GPIO_AF4_I2C2
#define MX_I2C2_SCL_GPIO_Pu                     GPIO_NOPULL
#define MX_I2C2_SCL_GPIO_Mode                   GPIO_MODE_AF_OD
#define MX_I2C2_SCL_PinAttribute                Free

/* NVIC Configuration */

/* NVIC I2C2_ER_IRQn */
#define MX_I2C2_ER_IRQn_interruptPremptionPriority 0
#define MX_I2C2_ER_IRQn_PriorityGroup           NVIC_PRIORITYGROUP_4
#define MX_I2C2_ER_IRQn_Subriority              0

/* NVIC I2C2_EV_IRQn */
#define MX_I2C2_EV_IRQn_interruptPremptionPriority 0
#define MX_I2C2_EV_IRQn_PriorityGroup           NVIC_PRIORITYGROUP_4
#define MX_I2C2_EV_IRQn_Subriority              0

/*-------------------------------- IWDG1      --------------------------------*/

#define MX_IWDG1                                1

/* GPIO Configuration */

/*-------------------------------- LPUART1    --------------------------------*/

#define MX_LPUART1                              1

/* GPIO Configuration */

/* Pin PA10 */
#define MX_LPUART1_RX_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_RX_Pin                       PA10
#define MX_LPUART1_RX_GPIOx                     GPIOA
#define MX_LPUART1_RX_GPIO_PuPd                 GPIO_NOPULL
#define MX_LPUART1_RX_GPIO_Pin                  GPIO_PIN_10
#define MX_LPUART1_RX_GPIO_AF                   GPIO_AF3_LPUART
#define MX_LPUART1_RX_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_LPUART1_RX_PinAttribute              Free

/* Pin PA9 */
#define MX_LPUART1_TX_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_LPUART1_TX_Pin                       PA9
#define MX_LPUART1_TX_GPIOx                     GPIOA
#define MX_LPUART1_TX_GPIO_PuPd                 GPIO_NOPULL
#define MX_LPUART1_TX_GPIO_Pin                  GPIO_PIN_9
#define MX_LPUART1_TX_GPIO_AF                   GPIO_AF3_LPUART
#define MX_LPUART1_TX_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_LPUART1_TX_PinAttribute              Free

/* DMA Configuration */

// /* DMA LPUART1_RX */
// #define MX_LPUART1_RX_DMA_Instance              BDMA_Channel0
// #define MX_LPUART1_RX_DMA_Priority              DMA_PRIORITY_LOW
// #define MX_LPUART1_RX_DMA_MemDataAlignment      DMA_MDATAALIGN_BYTE
// #define MX_LPUART1_RX_DMA_Mode                  DMA_NORMAL
// #define MX_LPUART1_RX_DMA_SyncRequestNumber     1
// #define MX_LPUART1_RX_DMA_Request               BDMA_REQUEST_LPUART1_RX
// #define MX_LPUART1_RX_DMA_SyncPolarity          HAL_DMAMUX_SYNC_NO_EVENT
// #define MX_LPUART1_RX_DMA_Direction             DMA_PERIPH_TO_MEMORY
// #define MX_LPUART1_RX_DMA_SignalID              NONE
// #define MX_LPUART1_RX_DMA_MemInc                DMA_MINC_ENABLE
// #define MX_LPUART1_RX_DMA_IpInstance
// #define MX_LPUART1_RX_DMA_RequestNumber         1
// #define MX_LPUART1_RX_DMA_EventEnable           DISABLE
// #define MX_LPUART1_RX_DMA_SyncEnable            DISABLE
// #define MX_LPUART1_RX_DMA_DMA_Handle
// #define MX_LPUART1_RX_DMA_PeriphDataAlignment   DMA_PDATAALIGN_BYTE
// #define MX_LPUART1_RX_DMA_Polarity              HAL_DMAMUX_REQ_GEN_RISING
// #define MX_LPUART1_RX_DMA_SyncSignalID          NONE
// #define MX_LPUART1_RX_DMA_PeriphInc             DMA_PINC_DISABLE

// /* DMA LPUART1_TX */
// #define MX_LPUART1_TX_DMA_Instance              BDMA_Channel1
// #define MX_LPUART1_TX_DMA_Priority              DMA_PRIORITY_LOW
// #define MX_LPUART1_TX_DMA_MemDataAlignment      DMA_MDATAALIGN_BYTE
// #define MX_LPUART1_TX_DMA_Mode                  DMA_NORMAL
// #define MX_LPUART1_TX_DMA_SyncRequestNumber     1
// #define MX_LPUART1_TX_DMA_Request               BDMA_REQUEST_LPUART1_TX
// #define MX_LPUART1_TX_DMA_SyncPolarity          HAL_DMAMUX_SYNC_NO_EVENT
// #define MX_LPUART1_TX_DMA_Direction             DMA_MEMORY_TO_PERIPH
// #define MX_LPUART1_TX_DMA_SignalID              NONE
// #define MX_LPUART1_TX_DMA_MemInc                DMA_MINC_ENABLE
// #define MX_LPUART1_TX_DMA_IpInstance
// #define MX_LPUART1_TX_DMA_RequestNumber         1
// #define MX_LPUART1_TX_DMA_EventEnable           DISABLE
// #define MX_LPUART1_TX_DMA_SyncEnable            DISABLE
// #define MX_LPUART1_TX_DMA_DMA_Handle
// #define MX_LPUART1_TX_DMA_PeriphDataAlignment   DMA_PDATAALIGN_BYTE
// #define MX_LPUART1_TX_DMA_Polarity              HAL_DMAMUX_REQ_GEN_RISING
// #define MX_LPUART1_TX_DMA_SyncSignalID          NONE
// #define MX_LPUART1_TX_DMA_PeriphInc             DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC LPUART1_IRQn */
#define MX_LPUART1_IRQn_interruptPremptionPriority 0
#define MX_LPUART1_IRQn_PriorityGroup           NVIC_PRIORITYGROUP_4
#define MX_LPUART1_IRQn_Subriority              0

/*-------------------------------- UART4      --------------------------------*/

#define MX_UART4                                1

#define MX_UART4_VM                             VM_ASYNC

/* GPIO Configuration */

/* Pin PI9 */
#define MX_UART4_RX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART4_RX_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_UART4_RX_Pin                         PI9
#define MX_UART4_RX_GPIOx                       GPIOI
#define MX_UART4_RX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART4_RX_GPIO_Pin                    GPIO_PIN_9
#define MX_UART4_RX_GPIO_AF                     GPIO_AF8_UART4
#define MX_UART4_RX_PinAttribute                Free

/* Pin PA12 */
#define MX_UART4_TX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART4_TX_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_UART4_TX_Pin                         PA12
#define MX_UART4_TX_GPIOx                       GPIOA
#define MX_UART4_TX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART4_TX_GPIO_Pin                    GPIO_PIN_12
#define MX_UART4_TX_GPIO_AF                     GPIO_AF6_UART4
#define MX_UART4_TX_PinAttribute                Free

/* DMA Configuration */

/* DMA UART4_RX */
#define MX_UART4_RX_DMA_Instance                DMA1_Stream6
#define MX_UART4_RX_DMA_FIFOMode                DMA_FIFOMODE_DISABLE
#define MX_UART4_RX_DMA_Priority                DMA_PRIORITY_LOW
#define MX_UART4_RX_DMA_MemDataAlignment        DMA_MDATAALIGN_BYTE
#define MX_UART4_RX_DMA_Mode                    DMA_NORMAL
#define MX_UART4_RX_DMA_SyncRequestNumber       1
#define MX_UART4_RX_DMA_Request                 DMA_REQUEST_UART4_RX
#define MX_UART4_RX_DMA_SyncPolarity            HAL_DMAMUX_SYNC_NO_EVENT
#define MX_UART4_RX_DMA_Direction               DMA_PERIPH_TO_MEMORY
#define MX_UART4_RX_DMA_SignalID                NONE
#define MX_UART4_RX_DMA_MemInc                  DMA_MINC_ENABLE
#define MX_UART4_RX_DMA_IpInstance
#define MX_UART4_RX_DMA_RequestNumber           1
#define MX_UART4_RX_DMA_EventEnable             DISABLE
#define MX_UART4_RX_DMA_SyncEnable              DISABLE
#define MX_UART4_RX_DMA_DMA_Handle
#define MX_UART4_RX_DMA_PeriphDataAlignment     DMA_PDATAALIGN_BYTE
#define MX_UART4_RX_DMA_Polarity                HAL_DMAMUX_REQ_GEN_RISING
#define MX_UART4_RX_DMA_SyncSignalID            NONE
#define MX_UART4_RX_DMA_PeriphInc               DMA_PINC_DISABLE

/* DMA UART4_TX */
#define MX_UART4_TX_DMA_Instance                DMA1_Stream7
#define MX_UART4_TX_DMA_FIFOMode                DMA_FIFOMODE_DISABLE
#define MX_UART4_TX_DMA_Priority                DMA_PRIORITY_LOW
#define MX_UART4_TX_DMA_MemDataAlignment        DMA_MDATAALIGN_BYTE
#define MX_UART4_TX_DMA_Mode                    DMA_NORMAL
#define MX_UART4_TX_DMA_SyncRequestNumber       1
#define MX_UART4_TX_DMA_Request                 DMA_REQUEST_UART4_TX
#define MX_UART4_TX_DMA_SyncPolarity            HAL_DMAMUX_SYNC_NO_EVENT
#define MX_UART4_TX_DMA_Direction               DMA_MEMORY_TO_PERIPH
#define MX_UART4_TX_DMA_SignalID                NONE
#define MX_UART4_TX_DMA_MemInc                  DMA_MINC_ENABLE
#define MX_UART4_TX_DMA_IpInstance
#define MX_UART4_TX_DMA_RequestNumber           1
#define MX_UART4_TX_DMA_EventEnable             DISABLE
#define MX_UART4_TX_DMA_SyncEnable              DISABLE
#define MX_UART4_TX_DMA_DMA_Handle
#define MX_UART4_TX_DMA_PeriphDataAlignment     DMA_PDATAALIGN_BYTE
#define MX_UART4_TX_DMA_Polarity                HAL_DMAMUX_REQ_GEN_RISING
#define MX_UART4_TX_DMA_SyncSignalID            NONE
#define MX_UART4_TX_DMA_PeriphInc               DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC UART4_IRQn */
#define MX_UART4_IRQn_interruptPremptionPriority 0
#define MX_UART4_IRQn_PriorityGroup             NVIC_PRIORITYGROUP_4
#define MX_UART4_IRQn_Subriority                0

/*-------------------------------- UART5      --------------------------------*/

#define MX_UART5                                1

#define MX_UART5_VM                             VM_ASYNC

/* GPIO Configuration */

/* Pin PB5 */
#define MX_UART5_RX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART5_RX_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_UART5_RX_Pin                         PB5
#define MX_UART5_RX_GPIOx                       GPIOB
#define MX_UART5_RX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART5_RX_GPIO_Pin                    GPIO_PIN_5
#define MX_UART5_RX_GPIO_AF                     GPIO_AF14_UART5
#define MX_UART5_RX_PinAttribute                Free

/* Pin PB13 */
#define MX_UART5_TX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART5_TX_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_UART5_TX_Pin                         PB13
#define MX_UART5_TX_GPIOx                       GPIOB
#define MX_UART5_TX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART5_TX_GPIO_Pin                    GPIO_PIN_13
#define MX_UART5_TX_GPIO_AF                     GPIO_AF14_UART5
#define MX_UART5_TX_PinAttribute                Free

/* DMA Configuration */

/* DMA UART5_RX */
#define MX_UART5_RX_DMA_Instance                DMA2_Stream0
#define MX_UART5_RX_DMA_FIFOMode                DMA_FIFOMODE_DISABLE
#define MX_UART5_RX_DMA_Priority                DMA_PRIORITY_LOW
#define MX_UART5_RX_DMA_MemDataAlignment        DMA_MDATAALIGN_BYTE
#define MX_UART5_RX_DMA_Mode                    DMA_NORMAL
#define MX_UART5_RX_DMA_SyncRequestNumber       1
#define MX_UART5_RX_DMA_Request                 DMA_REQUEST_UART5_RX
#define MX_UART5_RX_DMA_SyncPolarity            HAL_DMAMUX_SYNC_NO_EVENT
#define MX_UART5_RX_DMA_Direction               DMA_PERIPH_TO_MEMORY
#define MX_UART5_RX_DMA_SignalID                NONE
#define MX_UART5_RX_DMA_MemInc                  DMA_MINC_ENABLE
#define MX_UART5_RX_DMA_IpInstance
#define MX_UART5_RX_DMA_RequestNumber           1
#define MX_UART5_RX_DMA_EventEnable             DISABLE
#define MX_UART5_RX_DMA_SyncEnable              DISABLE
#define MX_UART5_RX_DMA_DMA_Handle
#define MX_UART5_RX_DMA_PeriphDataAlignment     DMA_PDATAALIGN_BYTE
#define MX_UART5_RX_DMA_Polarity                HAL_DMAMUX_REQ_GEN_RISING
#define MX_UART5_RX_DMA_SyncSignalID            NONE
#define MX_UART5_RX_DMA_PeriphInc               DMA_PINC_DISABLE

/* DMA UART5_TX */
#define MX_UART5_TX_DMA_Instance                DMA2_Stream1
#define MX_UART5_TX_DMA_FIFOMode                DMA_FIFOMODE_DISABLE
#define MX_UART5_TX_DMA_Priority                DMA_PRIORITY_LOW
#define MX_UART5_TX_DMA_MemDataAlignment        DMA_MDATAALIGN_BYTE
#define MX_UART5_TX_DMA_Mode                    DMA_NORMAL
#define MX_UART5_TX_DMA_SyncRequestNumber       1
#define MX_UART5_TX_DMA_Request                 DMA_REQUEST_UART5_TX
#define MX_UART5_TX_DMA_SyncPolarity            HAL_DMAMUX_SYNC_NO_EVENT
#define MX_UART5_TX_DMA_Direction               DMA_MEMORY_TO_PERIPH
#define MX_UART5_TX_DMA_SignalID                NONE
#define MX_UART5_TX_DMA_MemInc                  DMA_MINC_ENABLE
#define MX_UART5_TX_DMA_IpInstance
#define MX_UART5_TX_DMA_RequestNumber           1
#define MX_UART5_TX_DMA_EventEnable             DISABLE
#define MX_UART5_TX_DMA_SyncEnable              DISABLE
#define MX_UART5_TX_DMA_DMA_Handle
#define MX_UART5_TX_DMA_PeriphDataAlignment     DMA_PDATAALIGN_BYTE
#define MX_UART5_TX_DMA_Polarity                HAL_DMAMUX_REQ_GEN_RISING
#define MX_UART5_TX_DMA_SyncSignalID            NONE
#define MX_UART5_TX_DMA_PeriphInc               DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC UART5_IRQn */
#define MX_UART5_IRQn_interruptPremptionPriority 0
#define MX_UART5_IRQn_PriorityGroup             NVIC_PRIORITYGROUP_4
#define MX_UART5_IRQn_Subriority                0

/*-------------------------------- UART7      --------------------------------*/

#define MX_UART7                                1

#define MX_UART7_VM                             VM_ASYNC

/* GPIO Configuration */

/* Pin PF8 */
#define MX_UART7_DE_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_UART7_DE_Pin                         PF8
#define MX_UART7_DE_GPIOx                       GPIOF
#define MX_UART7_DE_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART7_DE_GPIO_Pin                    GPIO_PIN_8
#define MX_UART7_DE_GPIO_AF                     GPIO_AF7_UART7
#define MX_UART7_DE_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_UART7_DE_PinAttribute                Free

/* Pin PA15 (JTDI) */
#define MX_UART7_TX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART7_TX_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_UART7_TX_Pin                         PA15_JTDI
#define MX_UART7_TX_GPIOx                       GPIOA
#define MX_UART7_TX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART7_TX_GPIO_Pin                    GPIO_PIN_15
#define MX_UART7_TX_GPIO_AF                     GPIO_AF11_UART7
#define MX_UART7_TX_PinAttribute                Free

/* Pin PA8 */
#define MX_UART7_RX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART7_RX_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_UART7_RX_Pin                         PA8
#define MX_UART7_RX_GPIOx                       GPIOA
#define MX_UART7_RX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART7_RX_GPIO_Pin                    GPIO_PIN_8
#define MX_UART7_RX_GPIO_AF                     GPIO_AF11_UART7
#define MX_UART7_RX_PinAttribute                Free

/* DMA Configuration */

/* DMA UART7_TX */
#define MX_UART7_TX_DMA_Instance                DMA2_Stream5
#define MX_UART7_TX_DMA_FIFOMode                DMA_FIFOMODE_DISABLE
#define MX_UART7_TX_DMA_Priority                DMA_PRIORITY_LOW
#define MX_UART7_TX_DMA_MemDataAlignment        DMA_MDATAALIGN_BYTE
#define MX_UART7_TX_DMA_Mode                    DMA_NORMAL
#define MX_UART7_TX_DMA_SyncRequestNumber       1
#define MX_UART7_TX_DMA_Request                 DMA_REQUEST_UART7_TX
#define MX_UART7_TX_DMA_SyncPolarity            HAL_DMAMUX_SYNC_NO_EVENT
#define MX_UART7_TX_DMA_Direction               DMA_MEMORY_TO_PERIPH
#define MX_UART7_TX_DMA_SignalID                NONE
#define MX_UART7_TX_DMA_MemInc                  DMA_MINC_ENABLE
#define MX_UART7_TX_DMA_IpInstance
#define MX_UART7_TX_DMA_RequestNumber           1
#define MX_UART7_TX_DMA_EventEnable             DISABLE
#define MX_UART7_TX_DMA_SyncEnable              DISABLE
#define MX_UART7_TX_DMA_DMA_Handle
#define MX_UART7_TX_DMA_PeriphDataAlignment     DMA_PDATAALIGN_BYTE
#define MX_UART7_TX_DMA_Polarity                HAL_DMAMUX_REQ_GEN_RISING
#define MX_UART7_TX_DMA_SyncSignalID            NONE
#define MX_UART7_TX_DMA_PeriphInc               DMA_PINC_DISABLE

/* DMA UART7_RX */
#define MX_UART7_RX_DMA_Instance                DMA2_Stream4
#define MX_UART7_RX_DMA_FIFOMode                DMA_FIFOMODE_DISABLE
#define MX_UART7_RX_DMA_Priority                DMA_PRIORITY_LOW
#define MX_UART7_RX_DMA_MemDataAlignment        DMA_MDATAALIGN_BYTE
#define MX_UART7_RX_DMA_Mode                    DMA_NORMAL
#define MX_UART7_RX_DMA_SyncRequestNumber       1
#define MX_UART7_RX_DMA_Request                 DMA_REQUEST_UART7_RX
#define MX_UART7_RX_DMA_SyncPolarity            HAL_DMAMUX_SYNC_NO_EVENT
#define MX_UART7_RX_DMA_Direction               DMA_PERIPH_TO_MEMORY
#define MX_UART7_RX_DMA_SignalID                NONE
#define MX_UART7_RX_DMA_MemInc                  DMA_MINC_ENABLE
#define MX_UART7_RX_DMA_IpInstance
#define MX_UART7_RX_DMA_RequestNumber           1
#define MX_UART7_RX_DMA_EventEnable             DISABLE
#define MX_UART7_RX_DMA_SyncEnable              DISABLE
#define MX_UART7_RX_DMA_DMA_Handle
#define MX_UART7_RX_DMA_PeriphDataAlignment     DMA_PDATAALIGN_BYTE
#define MX_UART7_RX_DMA_Polarity                HAL_DMAMUX_REQ_GEN_RISING
#define MX_UART7_RX_DMA_SyncSignalID            NONE
#define MX_UART7_RX_DMA_PeriphInc               DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC UART7_IRQn */
#define MX_UART7_IRQn_interruptPremptionPriority 0
#define MX_UART7_IRQn_PriorityGroup             NVIC_PRIORITYGROUP_4
#define MX_UART7_IRQn_Subriority                0

/*-------------------------------- UART8      --------------------------------*/

#define MX_UART8                                1

#define MX_UART8_VM                             VM_ASYNC

/* GPIO Configuration */

/* Pin PJ8 */
#define MX_UART8_TX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART8_TX_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_UART8_TX_Pin                         PJ8
#define MX_UART8_TX_GPIOx                       GPIOJ
#define MX_UART8_TX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART8_TX_GPIO_Pin                    GPIO_PIN_8
#define MX_UART8_TX_GPIO_AF                     GPIO_AF8_UART8
#define MX_UART8_TX_PinAttribute                Free

/* Pin PJ9 */
#define MX_UART8_RX_GPIO_ModeDefaultPP          GPIO_MODE_AF_PP
#define MX_UART8_RX_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_UART8_RX_Pin                         PJ9
#define MX_UART8_RX_GPIOx                       GPIOJ
#define MX_UART8_RX_GPIO_PuPd                   GPIO_NOPULL
#define MX_UART8_RX_GPIO_Pin                    GPIO_PIN_9
#define MX_UART8_RX_GPIO_AF                     GPIO_AF8_UART8
#define MX_UART8_RX_PinAttribute                Free

/* DMA Configuration */

/* DMA UART8_TX */
#define MX_UART8_TX_DMA_Instance                DMA2_Stream7
#define MX_UART8_TX_DMA_FIFOMode                DMA_FIFOMODE_DISABLE
#define MX_UART8_TX_DMA_Priority                DMA_PRIORITY_LOW
#define MX_UART8_TX_DMA_MemDataAlignment        DMA_MDATAALIGN_BYTE
#define MX_UART8_TX_DMA_Mode                    DMA_NORMAL
#define MX_UART8_TX_DMA_SyncRequestNumber       1
#define MX_UART8_TX_DMA_Request                 DMA_REQUEST_UART8_TX
#define MX_UART8_TX_DMA_SyncPolarity            HAL_DMAMUX_SYNC_NO_EVENT
#define MX_UART8_TX_DMA_Direction               DMA_MEMORY_TO_PERIPH
#define MX_UART8_TX_DMA_SignalID                NONE
#define MX_UART8_TX_DMA_MemInc                  DMA_MINC_ENABLE
#define MX_UART8_TX_DMA_IpInstance
#define MX_UART8_TX_DMA_RequestNumber           1
#define MX_UART8_TX_DMA_EventEnable             DISABLE
#define MX_UART8_TX_DMA_SyncEnable              DISABLE
#define MX_UART8_TX_DMA_DMA_Handle
#define MX_UART8_TX_DMA_PeriphDataAlignment     DMA_PDATAALIGN_BYTE
#define MX_UART8_TX_DMA_Polarity                HAL_DMAMUX_REQ_GEN_RISING
#define MX_UART8_TX_DMA_SyncSignalID            NONE
#define MX_UART8_TX_DMA_PeriphInc               DMA_PINC_DISABLE

/* DMA UART8_RX */
#define MX_UART8_RX_DMA_Instance                DMA2_Stream6
#define MX_UART8_RX_DMA_FIFOMode                DMA_FIFOMODE_DISABLE
#define MX_UART8_RX_DMA_Priority                DMA_PRIORITY_LOW
#define MX_UART8_RX_DMA_MemDataAlignment        DMA_MDATAALIGN_BYTE
#define MX_UART8_RX_DMA_Mode                    DMA_NORMAL
#define MX_UART8_RX_DMA_SyncRequestNumber       1
#define MX_UART8_RX_DMA_Request                 DMA_REQUEST_UART8_RX
#define MX_UART8_RX_DMA_SyncPolarity            HAL_DMAMUX_SYNC_NO_EVENT
#define MX_UART8_RX_DMA_Direction               DMA_PERIPH_TO_MEMORY
#define MX_UART8_RX_DMA_SignalID                NONE
#define MX_UART8_RX_DMA_MemInc                  DMA_MINC_ENABLE
#define MX_UART8_RX_DMA_IpInstance
#define MX_UART8_RX_DMA_RequestNumber           1
#define MX_UART8_RX_DMA_EventEnable             DISABLE
#define MX_UART8_RX_DMA_SyncEnable              DISABLE
#define MX_UART8_RX_DMA_DMA_Handle
#define MX_UART8_RX_DMA_PeriphDataAlignment     DMA_PDATAALIGN_BYTE
#define MX_UART8_RX_DMA_Polarity                HAL_DMAMUX_REQ_GEN_RISING
#define MX_UART8_RX_DMA_SyncSignalID            NONE
#define MX_UART8_RX_DMA_PeriphInc               DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC UART8_IRQn */
#define MX_UART8_IRQn_interruptPremptionPriority 0
#define MX_UART8_IRQn_PriorityGroup             NVIC_PRIORITYGROUP_4
#define MX_UART8_IRQn_Subriority                0

/*-------------------------------- USART1     --------------------------------*/

#define MX_USART1                               1

#define MX_USART1_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PB14 */
#define MX_USART1_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART1_TX_Pin                        PB14
#define MX_USART1_TX_GPIOx                      GPIOB
#define MX_USART1_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_TX_GPIO_Pin                   GPIO_PIN_14
#define MX_USART1_TX_GPIO_AF                    GPIO_AF4_USART1
#define MX_USART1_TX_PinAttribute               Free

/* Pin PB15 */
#define MX_USART1_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART1_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART1_RX_Pin                        PB15
#define MX_USART1_RX_GPIOx                      GPIOB
#define MX_USART1_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART1_RX_GPIO_Pin                   GPIO_PIN_15
#define MX_USART1_RX_GPIO_AF                    GPIO_AF4_USART1
#define MX_USART1_RX_PinAttribute               Free

/* DMA Configuration */

/* DMA USART1_TX */
#define MX_USART1_TX_DMA_Instance               DMA1_Stream1
#define MX_USART1_TX_DMA_FIFOMode               DMA_FIFOMODE_DISABLE
#define MX_USART1_TX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART1_TX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART1_TX_DMA_Mode                   DMA_NORMAL
#define MX_USART1_TX_DMA_SyncRequestNumber      1
#define MX_USART1_TX_DMA_Request                DMA_REQUEST_USART1_TX
#define MX_USART1_TX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART1_TX_DMA_Direction              DMA_MEMORY_TO_PERIPH
#define MX_USART1_TX_DMA_SignalID               NONE
#define MX_USART1_TX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART1_TX_DMA_IpInstance
#define MX_USART1_TX_DMA_RequestNumber          1
#define MX_USART1_TX_DMA_EventEnable            DISABLE
#define MX_USART1_TX_DMA_SyncEnable             DISABLE
#define MX_USART1_TX_DMA_DMA_Handle
#define MX_USART1_TX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART1_TX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART1_TX_DMA_SyncSignalID           NONE
#define MX_USART1_TX_DMA_PeriphInc              DMA_PINC_DISABLE

/* DMA USART1_RX */
#define MX_USART1_RX_DMA_Instance               DMA1_Stream0
#define MX_USART1_RX_DMA_FIFOMode               DMA_FIFOMODE_DISABLE
#define MX_USART1_RX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART1_RX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART1_RX_DMA_Mode                   DMA_NORMAL
#define MX_USART1_RX_DMA_SyncRequestNumber      1
#define MX_USART1_RX_DMA_Request                DMA_REQUEST_USART1_RX
#define MX_USART1_RX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART1_RX_DMA_Direction              DMA_PERIPH_TO_MEMORY
#define MX_USART1_RX_DMA_SignalID               NONE
#define MX_USART1_RX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART1_RX_DMA_IpInstance
#define MX_USART1_RX_DMA_RequestNumber          1
#define MX_USART1_RX_DMA_EventEnable            DISABLE
#define MX_USART1_RX_DMA_SyncEnable             DISABLE
#define MX_USART1_RX_DMA_DMA_Handle
#define MX_USART1_RX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART1_RX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART1_RX_DMA_SyncSignalID           NONE
#define MX_USART1_RX_DMA_PeriphInc              DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC USART1_IRQn */
#define MX_USART1_IRQn_interruptPremptionPriority 0
#define MX_USART1_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USART1_IRQn_Subriority               0

/*-------------------------------- USART2     --------------------------------*/

#define MX_USART2                               1

#define MX_USART2_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PD5 */
#define MX_USART2_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART2_TX_Pin                        PD5
#define MX_USART2_TX_GPIOx                      GPIOD
#define MX_USART2_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_TX_GPIO_Pin                   GPIO_PIN_5
#define MX_USART2_TX_GPIO_AF                    GPIO_AF7_USART2
#define MX_USART2_TX_PinAttribute               Free

/* Pin PD6 */
#define MX_USART2_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART2_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART2_RX_Pin                        PD6
#define MX_USART2_RX_GPIOx                      GPIOD
#define MX_USART2_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART2_RX_GPIO_Pin                   GPIO_PIN_6
#define MX_USART2_RX_GPIO_AF                    GPIO_AF7_USART2
#define MX_USART2_RX_PinAttribute               Free

/* DMA Configuration */

/* DMA USART2_TX */
#define MX_USART2_TX_DMA_Instance               DMA1_Stream3
#define MX_USART2_TX_DMA_FIFOMode               DMA_FIFOMODE_DISABLE
#define MX_USART2_TX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART2_TX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART2_TX_DMA_Mode                   DMA_NORMAL
#define MX_USART2_TX_DMA_SyncRequestNumber      1
#define MX_USART2_TX_DMA_Request                DMA_REQUEST_USART2_TX
#define MX_USART2_TX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART2_TX_DMA_Direction              DMA_MEMORY_TO_PERIPH
#define MX_USART2_TX_DMA_SignalID               NONE
#define MX_USART2_TX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART2_TX_DMA_IpInstance
#define MX_USART2_TX_DMA_RequestNumber          1
#define MX_USART2_TX_DMA_EventEnable            DISABLE
#define MX_USART2_TX_DMA_SyncEnable             DISABLE
#define MX_USART2_TX_DMA_DMA_Handle
#define MX_USART2_TX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART2_TX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART2_TX_DMA_SyncSignalID           NONE
#define MX_USART2_TX_DMA_PeriphInc              DMA_PINC_DISABLE

/* DMA USART2_RX */
#define MX_USART2_RX_DMA_Instance               DMA1_Stream2
#define MX_USART2_RX_DMA_FIFOMode               DMA_FIFOMODE_DISABLE
#define MX_USART2_RX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART2_RX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART2_RX_DMA_Mode                   DMA_NORMAL
#define MX_USART2_RX_DMA_SyncRequestNumber      1
#define MX_USART2_RX_DMA_Request                DMA_REQUEST_USART2_RX
#define MX_USART2_RX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART2_RX_DMA_Direction              DMA_PERIPH_TO_MEMORY
#define MX_USART2_RX_DMA_SignalID               NONE
#define MX_USART2_RX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART2_RX_DMA_IpInstance
#define MX_USART2_RX_DMA_RequestNumber          1
#define MX_USART2_RX_DMA_EventEnable            DISABLE
#define MX_USART2_RX_DMA_SyncEnable             DISABLE
#define MX_USART2_RX_DMA_DMA_Handle
#define MX_USART2_RX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART2_RX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART2_RX_DMA_SyncSignalID           NONE
#define MX_USART2_RX_DMA_PeriphInc              DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC USART2_IRQn */
#define MX_USART2_IRQn_interruptPremptionPriority 0
#define MX_USART2_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USART2_IRQn_Subriority               0

/*-------------------------------- USART3     --------------------------------*/

#define MX_USART3                               1

#define MX_USART3_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PB10 */
#define MX_USART3_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART3_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART3_TX_Pin                        PB10
#define MX_USART3_TX_GPIOx                      GPIOB
#define MX_USART3_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART3_TX_GPIO_Pin                   GPIO_PIN_10
#define MX_USART3_TX_GPIO_AF                    GPIO_AF7_USART3
#define MX_USART3_TX_PinAttribute               Free

/* Pin PB11 */
#define MX_USART3_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART3_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART3_RX_Pin                        PB11
#define MX_USART3_RX_GPIOx                      GPIOB
#define MX_USART3_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART3_RX_GPIO_Pin                   GPIO_PIN_11
#define MX_USART3_RX_GPIO_AF                    GPIO_AF7_USART3
#define MX_USART3_RX_PinAttribute               Free

/* DMA Configuration */

/* DMA USART3_TX */
#define MX_USART3_TX_DMA_Instance               DMA1_Stream5
#define MX_USART3_TX_DMA_FIFOMode               DMA_FIFOMODE_DISABLE
#define MX_USART3_TX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART3_TX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART3_TX_DMA_Mode                   DMA_NORMAL
#define MX_USART3_TX_DMA_SyncRequestNumber      1
#define MX_USART3_TX_DMA_Request                DMA_REQUEST_USART3_TX
#define MX_USART3_TX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART3_TX_DMA_Direction              DMA_MEMORY_TO_PERIPH
#define MX_USART3_TX_DMA_SignalID               NONE
#define MX_USART3_TX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART3_TX_DMA_IpInstance
#define MX_USART3_TX_DMA_RequestNumber          1
#define MX_USART3_TX_DMA_EventEnable            DISABLE
#define MX_USART3_TX_DMA_SyncEnable             DISABLE
#define MX_USART3_TX_DMA_DMA_Handle
#define MX_USART3_TX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART3_TX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART3_TX_DMA_SyncSignalID           NONE
#define MX_USART3_TX_DMA_PeriphInc              DMA_PINC_DISABLE

/* DMA USART3_RX */
#define MX_USART3_RX_DMA_Instance               DMA1_Stream4
#define MX_USART3_RX_DMA_FIFOMode               DMA_FIFOMODE_DISABLE
#define MX_USART3_RX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART3_RX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART3_RX_DMA_Mode                   DMA_NORMAL
#define MX_USART3_RX_DMA_SyncRequestNumber      1
#define MX_USART3_RX_DMA_Request                DMA_REQUEST_USART3_RX
#define MX_USART3_RX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART3_RX_DMA_Direction              DMA_PERIPH_TO_MEMORY
#define MX_USART3_RX_DMA_SignalID               NONE
#define MX_USART3_RX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART3_RX_DMA_IpInstance
#define MX_USART3_RX_DMA_RequestNumber          1
#define MX_USART3_RX_DMA_EventEnable            DISABLE
#define MX_USART3_RX_DMA_SyncEnable             DISABLE
#define MX_USART3_RX_DMA_DMA_Handle
#define MX_USART3_RX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART3_RX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART3_RX_DMA_SyncSignalID           NONE
#define MX_USART3_RX_DMA_PeriphInc              DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC USART3_IRQn */
#define MX_USART3_IRQn_interruptPremptionPriority 0
#define MX_USART3_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USART3_IRQn_Subriority               0

/*-------------------------------- USART6     --------------------------------*/

#define MX_USART6                               1

#define MX_USART6_VM                            VM_ASYNC

/* GPIO Configuration */

/* Pin PG9 */
#define MX_USART6_RX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART6_RX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART6_RX_Pin                        PG9
#define MX_USART6_RX_GPIOx                      GPIOG
#define MX_USART6_RX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART6_RX_GPIO_Pin                   GPIO_PIN_9
#define MX_USART6_RX_GPIO_AF                    GPIO_AF7_USART6
#define MX_USART6_RX_PinAttribute               Free

/* Pin PG14 */
#define MX_USART6_TX_GPIO_ModeDefaultPP         GPIO_MODE_AF_PP
#define MX_USART6_TX_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_USART6_TX_Pin                        PG14
#define MX_USART6_TX_GPIOx                      GPIOG
#define MX_USART6_TX_GPIO_PuPd                  GPIO_NOPULL
#define MX_USART6_TX_GPIO_Pin                   GPIO_PIN_14
#define MX_USART6_TX_GPIO_AF                    GPIO_AF7_USART6
#define MX_USART6_TX_PinAttribute               Free

/* DMA Configuration */

/* DMA USART6_RX */
#define MX_USART6_RX_DMA_Instance               DMA2_Stream2
#define MX_USART6_RX_DMA_FIFOMode               DMA_FIFOMODE_DISABLE
#define MX_USART6_RX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART6_RX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART6_RX_DMA_Mode                   DMA_NORMAL
#define MX_USART6_RX_DMA_SyncRequestNumber      1
#define MX_USART6_RX_DMA_Request                DMA_REQUEST_USART6_RX
#define MX_USART6_RX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART6_RX_DMA_Direction              DMA_PERIPH_TO_MEMORY
#define MX_USART6_RX_DMA_SignalID               NONE
#define MX_USART6_RX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART6_RX_DMA_IpInstance
#define MX_USART6_RX_DMA_RequestNumber          1
#define MX_USART6_RX_DMA_EventEnable            DISABLE
#define MX_USART6_RX_DMA_SyncEnable             DISABLE
#define MX_USART6_RX_DMA_DMA_Handle
#define MX_USART6_RX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART6_RX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART6_RX_DMA_SyncSignalID           NONE
#define MX_USART6_RX_DMA_PeriphInc              DMA_PINC_DISABLE

/* DMA USART6_TX */
#define MX_USART6_TX_DMA_Instance               DMA2_Stream3
#define MX_USART6_TX_DMA_FIFOMode               DMA_FIFOMODE_DISABLE
#define MX_USART6_TX_DMA_Priority               DMA_PRIORITY_LOW
#define MX_USART6_TX_DMA_MemDataAlignment       DMA_MDATAALIGN_BYTE
#define MX_USART6_TX_DMA_Mode                   DMA_NORMAL
#define MX_USART6_TX_DMA_SyncRequestNumber      1
#define MX_USART6_TX_DMA_Request                DMA_REQUEST_USART6_TX
#define MX_USART6_TX_DMA_SyncPolarity           HAL_DMAMUX_SYNC_NO_EVENT
#define MX_USART6_TX_DMA_Direction              DMA_MEMORY_TO_PERIPH
#define MX_USART6_TX_DMA_SignalID               NONE
#define MX_USART6_TX_DMA_MemInc                 DMA_MINC_ENABLE
#define MX_USART6_TX_DMA_IpInstance
#define MX_USART6_TX_DMA_RequestNumber          1
#define MX_USART6_TX_DMA_EventEnable            DISABLE
#define MX_USART6_TX_DMA_SyncEnable             DISABLE
#define MX_USART6_TX_DMA_DMA_Handle
#define MX_USART6_TX_DMA_PeriphDataAlignment    DMA_PDATAALIGN_BYTE
#define MX_USART6_TX_DMA_Polarity               HAL_DMAMUX_REQ_GEN_RISING
#define MX_USART6_TX_DMA_SyncSignalID           NONE
#define MX_USART6_TX_DMA_PeriphInc              DMA_PINC_DISABLE

/* NVIC Configuration */

/* NVIC USART6_IRQn */
#define MX_USART6_IRQn_interruptPremptionPriority 0
#define MX_USART6_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_USART6_IRQn_Subriority               0

/*-------------------------------- QUADSPI    --------------------------------*/

#define MX_QUADSPI                              1

/* GPIO Configuration */

/* Pin PF10 */
#define MX_QUADSPI_CLK_GPIO_Speed               GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI_CLK_Pin                      PF10
#define MX_QUADSPI_CLK_GPIOx                    GPIOF
#define MX_QUADSPI_CLK_GPIO_PuPd                GPIO_NOPULL
#define MX_QUADSPI_CLK_GPIO_Pin                 GPIO_PIN_10
#define MX_QUADSPI_CLK_GPIO_AF                  GPIO_AF9_QUADSPI
#define MX_QUADSPI_CLK_GPIO_Mode                GPIO_MODE_AF_PP
#define MX_QUADSPI_CLK_PinAttribute             Free

/* Pin PG6 */
#define MX_QUADSPI_BK1_NCS_GPIO_Speed           GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI_BK1_NCS_Pin                  PG6
#define MX_QUADSPI_BK1_NCS_GPIOx                GPIOG
#define MX_QUADSPI_BK1_NCS_GPIO_PuPd            GPIO_NOPULL
#define MX_QUADSPI_BK1_NCS_GPIO_Pin             GPIO_PIN_6
#define MX_QUADSPI_BK1_NCS_GPIO_AF              GPIO_AF10_QUADSPI
#define MX_QUADSPI_BK1_NCS_GPIO_Mode            GPIO_MODE_AF_PP
#define MX_QUADSPI_BK1_NCS_PinAttribute         Free

/* Pin PF6 */
#define MX_QUADSPI_BK1_IO3_GPIO_Speed           GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI_BK1_IO3_Pin                  PF6
#define MX_QUADSPI_BK1_IO3_GPIOx                GPIOF
#define MX_QUADSPI_BK1_IO3_GPIO_PuPd            GPIO_NOPULL
#define MX_QUADSPI_BK1_IO3_GPIO_Pin             GPIO_PIN_6
#define MX_QUADSPI_BK1_IO3_GPIO_AF              GPIO_AF9_QUADSPI
#define MX_QUADSPI_BK1_IO3_GPIO_Mode            GPIO_MODE_AF_PP
#define MX_QUADSPI_BK1_IO3_PinAttribute         Free

/* Pin PE2 */
#define MX_QUADSPI_BK1_IO2_GPIO_Speed           GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI_BK1_IO2_Pin                  PE2
#define MX_QUADSPI_BK1_IO2_GPIOx                GPIOE
#define MX_QUADSPI_BK1_IO2_GPIO_PuPd            GPIO_NOPULL
#define MX_QUADSPI_BK1_IO2_GPIO_Pin             GPIO_PIN_2
#define MX_QUADSPI_BK1_IO2_GPIO_AF              GPIO_AF9_QUADSPI
#define MX_QUADSPI_BK1_IO2_GPIO_Mode            GPIO_MODE_AF_PP
#define MX_QUADSPI_BK1_IO2_PinAttribute         Free

/* Pin PF9 */
#define MX_QUADSPI_BK1_IO1_GPIO_Speed           GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI_BK1_IO1_Pin                  PF9
#define MX_QUADSPI_BK1_IO1_GPIOx                GPIOF
#define MX_QUADSPI_BK1_IO1_GPIO_PuPd            GPIO_NOPULL
#define MX_QUADSPI_BK1_IO1_GPIO_Pin             GPIO_PIN_9
#define MX_QUADSPI_BK1_IO1_GPIO_AF              GPIO_AF10_QUADSPI
#define MX_QUADSPI_BK1_IO1_GPIO_Mode            GPIO_MODE_AF_PP
#define MX_QUADSPI_BK1_IO1_PinAttribute         Free

/* Pin PD11 */
#define MX_QUADSPI_BK1_IO0_GPIO_Speed           GPIO_SPEED_FREQ_LOW
#define MX_QUADSPI_BK1_IO0_Pin                  PD11
#define MX_QUADSPI_BK1_IO0_GPIOx                GPIOD
#define MX_QUADSPI_BK1_IO0_GPIO_PuPd            GPIO_NOPULL
#define MX_QUADSPI_BK1_IO0_GPIO_Pin             GPIO_PIN_11
#define MX_QUADSPI_BK1_IO0_GPIO_AF              GPIO_AF9_QUADSPI
#define MX_QUADSPI_BK1_IO0_GPIO_Mode            GPIO_MODE_AF_PP
#define MX_QUADSPI_BK1_IO0_PinAttribute         Free

/*-------------------------------- SDMMC1     --------------------------------*/

#define MX_SDMMC1                               1

/* GPIO Configuration */

/* Pin PD2 */
#define MX_SDMMC1_CMD_Pin                       PD2
#define MX_SDMMC1_CMD_GPIOx                     GPIOD
#define MX_SDMMC1_CMD_GPIO_PuPd                 GPIO_NOPULL
#define MX_SDMMC1_CMD_GPIO_Speed_High_Default   GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_CMD_GPIO_Pin                  GPIO_PIN_2
#define MX_SDMMC1_CMD_GPIO_AF                   GPIO_AF12_SDIO1
#define MX_SDMMC1_CMD_GPIO_Mode                 GPIO_MODE_AF_PP
#define MX_SDMMC1_CMD_PinAttribute              Free

/* Pin PC8 */
#define MX_SDMMC1_D0_Pin                        PC8
#define MX_SDMMC1_D0_GPIOx                      GPIOC
#define MX_SDMMC1_D0_GPIO_PuPd                  GPIO_NOPULL
#define MX_SDMMC1_D0_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D0_GPIO_Pin                   GPIO_PIN_8
#define MX_SDMMC1_D0_GPIO_AF                    GPIO_AF12_SDIO1
#define MX_SDMMC1_D0_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_SDMMC1_D0_PinAttribute               Free

/* Pin PC9 */
#define MX_SDMMC1_D1_Pin                        PC9
#define MX_SDMMC1_D1_GPIOx                      GPIOC
#define MX_SDMMC1_D1_GPIO_PuPd                  GPIO_NOPULL
#define MX_SDMMC1_D1_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D1_GPIO_Pin                   GPIO_PIN_9
#define MX_SDMMC1_D1_GPIO_AF                    GPIO_AF12_SDIO1
#define MX_SDMMC1_D1_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_SDMMC1_D1_PinAttribute               Free

/* Pin PC10 */
#define MX_SDMMC1_D2_Pin                        PC10
#define MX_SDMMC1_D2_GPIOx                      GPIOC
#define MX_SDMMC1_D2_GPIO_PuPd                  GPIO_NOPULL
#define MX_SDMMC1_D2_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D2_GPIO_Pin                   GPIO_PIN_10
#define MX_SDMMC1_D2_GPIO_AF                    GPIO_AF12_SDIO1
#define MX_SDMMC1_D2_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_SDMMC1_D2_PinAttribute               Free

/* Pin PC11 */
#define MX_SDMMC1_D3_Pin                        PC11
#define MX_SDMMC1_D3_GPIOx                      GPIOC
#define MX_SDMMC1_D3_GPIO_PuPd                  GPIO_NOPULL
#define MX_SDMMC1_D3_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_D3_GPIO_Pin                   GPIO_PIN_11
#define MX_SDMMC1_D3_GPIO_AF                    GPIO_AF12_SDIO1
#define MX_SDMMC1_D3_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_SDMMC1_D3_PinAttribute               Free

/* Pin PC12 */
#define MX_SDMMC1_CK_Pin                        PC12
#define MX_SDMMC1_CK_GPIOx                      GPIOC
#define MX_SDMMC1_CK_GPIO_PuPd                  GPIO_NOPULL
#define MX_SDMMC1_CK_GPIO_Speed_High_Default    GPIO_SPEED_FREQ_VERY_HIGH
#define MX_SDMMC1_CK_GPIO_Pin                   GPIO_PIN_12
#define MX_SDMMC1_CK_GPIO_AF                    GPIO_AF12_SDIO1
#define MX_SDMMC1_CK_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_SDMMC1_CK_PinAttribute               Free

/* NVIC Configuration */

/* NVIC SDMMC1_IRQn */
#define MX_SDMMC1_IRQn_interruptPremptionPriority 0
#define MX_SDMMC1_IRQn_PriorityGroup            NVIC_PRIORITYGROUP_4
#define MX_SDMMC1_IRQn_Subriority               0

/*-------------------------------- SPI1       --------------------------------*/

#define MX_SPI1                                 1

/* GPIO Configuration */

/* Pin PG10 */
#define MX_SPI1_NSS_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_SPI1_NSS_Pin                         PG10
#define MX_SPI1_NSS_GPIOx                       GPIOG
#define MX_SPI1_NSS_GPIO_PuPd                   GPIO_NOPULL
#define MX_SPI1_NSS_GPIO_Pin                    GPIO_PIN_10
#define MX_SPI1_NSS_GPIO_AF                     GPIO_AF5_SPI1
#define MX_SPI1_NSS_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_SPI1_NSS_PinAttribute                Free

/* Pin PB4 (NJTRST) */
#define MX_SPI1_MISO_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_SPI1_MISO_Pin                        PB4_NJTRST
#define MX_SPI1_MISO_GPIOx                      GPIOB
#define MX_SPI1_MISO_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI1_MISO_GPIO_Pin                   GPIO_PIN_4
#define MX_SPI1_MISO_GPIO_AF                    GPIO_AF5_SPI1
#define MX_SPI1_MISO_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_SPI1_MISO_PinAttribute               Free

/* Pin PD7 */
#define MX_SPI1_MOSI_GPIO_Speed                 GPIO_SPEED_FREQ_LOW
#define MX_SPI1_MOSI_Pin                        PD7
#define MX_SPI1_MOSI_GPIOx                      GPIOD
#define MX_SPI1_MOSI_GPIO_PuPd                  GPIO_NOPULL
#define MX_SPI1_MOSI_GPIO_Pin                   GPIO_PIN_7
#define MX_SPI1_MOSI_GPIO_AF                    GPIO_AF5_SPI1
#define MX_SPI1_MOSI_GPIO_Mode                  GPIO_MODE_AF_PP
#define MX_SPI1_MOSI_PinAttribute               Free

/* Pin PA5 */
#define MX_SPI1_SCK_GPIO_Speed                  GPIO_SPEED_FREQ_LOW
#define MX_SPI1_SCK_Pin                         PA5
#define MX_SPI1_SCK_GPIOx                       GPIOA
#define MX_SPI1_SCK_GPIO_PuPd                   GPIO_NOPULL
#define MX_SPI1_SCK_GPIO_Pin                    GPIO_PIN_5
#define MX_SPI1_SCK_GPIO_AF                     GPIO_AF5_SPI1
#define MX_SPI1_SCK_GPIO_Mode                   GPIO_MODE_AF_PP
#define MX_SPI1_SCK_PinAttribute                Free

/* NVIC Configuration */

/* NVIC SPI1_IRQn */
#define MX_SPI1_IRQn_interruptPremptionPriority 0
#define MX_SPI1_IRQn_PriorityGroup              NVIC_PRIORITYGROUP_4
#define MX_SPI1_IRQn_Subriority                 0

/*-------------------------------- SYS        --------------------------------*/

#define MX_SYS                                  1

/* GPIO Configuration */

/*-------------------------------- TIM3       --------------------------------*/

#define MX_TIM3                                 1

/* GPIO Configuration */

/* Pin PB0 */
#define MX_S_TIM3_CH3_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM3_CH3_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM3_CH3_Pin                       PB0
#define MX_S_TIM3_CH3_GPIOx                     GPIOB
#define MX_S_TIM3_CH3_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM3_CH3_GPIO_Pin                  GPIO_PIN_0
#define MX_S_TIM3_CH3_GPIO_AF                   GPIO_AF2_TIM3
#define MX_S_TIM3_CH3_PinAttribute              Free

/* Pin PB1 */
#define MX_S_TIM3_CH4_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM3_CH4_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM3_CH4_Pin                       PB1
#define MX_S_TIM3_CH4_GPIOx                     GPIOB
#define MX_S_TIM3_CH4_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM3_CH4_GPIO_Pin                  GPIO_PIN_1
#define MX_S_TIM3_CH4_GPIO_AF                   GPIO_AF2_TIM3
#define MX_S_TIM3_CH4_PinAttribute              Free

/* Pin PC6 */
#define MX_S_TIM3_CH1_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM3_CH1_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM3_CH1_Pin                       PC6
#define MX_S_TIM3_CH1_GPIOx                     GPIOC
#define MX_S_TIM3_CH1_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM3_CH1_GPIO_Pin                  GPIO_PIN_6
#define MX_S_TIM3_CH1_GPIO_AF                   GPIO_AF2_TIM3
#define MX_S_TIM3_CH1_PinAttribute              Free

/* Pin PC7 */
#define MX_S_TIM3_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM3_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM3_CH2_Pin                       PC7
#define MX_S_TIM3_CH2_GPIOx                     GPIOC
#define MX_S_TIM3_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM3_CH2_GPIO_Pin                  GPIO_PIN_7
#define MX_S_TIM3_CH2_GPIO_AF                   GPIO_AF2_TIM3
#define MX_S_TIM3_CH2_PinAttribute              Free

/*-------------------------------- TIM4       --------------------------------*/

#define MX_TIM4                                 1

/* GPIO Configuration */

/* Pin PB9 */
#define MX_S_TIM4_CH4_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM4_CH4_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM4_CH4_Pin                       PB9
#define MX_S_TIM4_CH4_GPIOx                     GPIOB
#define MX_S_TIM4_CH4_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM4_CH4_GPIO_Pin                  GPIO_PIN_9
#define MX_S_TIM4_CH4_GPIO_AF                   GPIO_AF2_TIM4
#define MX_S_TIM4_CH4_PinAttribute              Free
#define MX_S_TIM4_CH4_GPIO_FM9                  __NULL

/* Pin PD12 */
#define MX_S_TIM4_CH1_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM4_CH1_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM4_CH1_Pin                       PD12
#define MX_S_TIM4_CH1_GPIOx                     GPIOD
#define MX_S_TIM4_CH1_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM4_CH1_GPIO_Pin                  GPIO_PIN_12
#define MX_S_TIM4_CH1_GPIO_AF                   GPIO_AF2_TIM4
#define MX_S_TIM4_CH1_PinAttribute              Free

/* Pin PD13 */
#define MX_S_TIM4_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM4_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM4_CH2_Pin                       PD13
#define MX_S_TIM4_CH2_GPIOx                     GPIOD
#define MX_S_TIM4_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM4_CH2_GPIO_Pin                  GPIO_PIN_13
#define MX_S_TIM4_CH2_GPIO_AF                   GPIO_AF2_TIM4
#define MX_S_TIM4_CH2_PinAttribute              Free

/* Pin PB8 */
#define MX_S_TIM4_CH3_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM4_CH3_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM4_CH3_Pin                       PB8
#define MX_S_TIM4_CH3_GPIOx                     GPIOB
#define MX_S_TIM4_CH3_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM4_CH3_GPIO_Pin                  GPIO_PIN_8
#define MX_S_TIM4_CH3_GPIO_FM8                  __NULL
#define MX_S_TIM4_CH3_GPIO_AF                   GPIO_AF2_TIM4
#define MX_S_TIM4_CH3_PinAttribute              Free

/*-------------------------------- TIM5       --------------------------------*/

#define MX_TIM5                                 1

/* GPIO Configuration */

/* Pin PH12 */
#define MX_S_TIM5_CH3_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM5_CH3_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM5_CH3_Pin                       PH12
#define MX_S_TIM5_CH3_GPIOx                     GPIOH
#define MX_S_TIM5_CH3_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM5_CH3_GPIO_Pin                  GPIO_PIN_12
#define MX_S_TIM5_CH3_GPIO_AF                   GPIO_AF2_TIM5
#define MX_S_TIM5_CH3_PinAttribute              Free

/* Pin PI0 */
#define MX_S_TIM5_CH4_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM5_CH4_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM5_CH4_Pin                       PI0
#define MX_S_TIM5_CH4_GPIOx                     GPIOI
#define MX_S_TIM5_CH4_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM5_CH4_GPIO_Pin                  GPIO_PIN_0
#define MX_S_TIM5_CH4_GPIO_AF                   GPIO_AF2_TIM5
#define MX_S_TIM5_CH4_PinAttribute              Free

/* Pin PH10 */
#define MX_S_TIM5_CH1_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM5_CH1_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM5_CH1_Pin                       PH10
#define MX_S_TIM5_CH1_GPIOx                     GPIOH
#define MX_S_TIM5_CH1_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM5_CH1_GPIO_Pin                  GPIO_PIN_10
#define MX_S_TIM5_CH1_GPIO_AF                   GPIO_AF2_TIM5
#define MX_S_TIM5_CH1_PinAttribute              Free

/* Pin PH11 */
#define MX_S_TIM5_CH2_GPIO_ModeDefaultPP        GPIO_MODE_AF_PP
#define MX_S_TIM5_CH2_GPIO_Speed                GPIO_SPEED_FREQ_LOW
#define MX_S_TIM5_CH2_Pin                       PH11
#define MX_S_TIM5_CH2_GPIOx                     GPIOH
#define MX_S_TIM5_CH2_GPIO_PuPd                 GPIO_NOPULL
#define MX_S_TIM5_CH2_GPIO_Pin                  GPIO_PIN_11
#define MX_S_TIM5_CH2_GPIO_AF                   GPIO_AF2_TIM5
#define MX_S_TIM5_CH2_PinAttribute              Free

/*-------------------------------- NVIC       --------------------------------*/

#define MX_NVIC                                 1

/*-------------------------------- GPIO       --------------------------------*/

#define MX_GPIO                                 1

/* GPIO Configuration */

/* Pin PC13 */
#define MX_PC13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PC13_Pin                             PC13
#define MX_PC13_GPIOx                           GPIOC
#define MX_PC13_PinState                        GPIO_PIN_RESET
#define MX_PC13_GPIO_PuPd                       GPIO_NOPULL
#define MX_TP4                                  PC13
#define MX_PC13_GPIO_Pin                        GPIO_PIN_13
#define MX_PC13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PE6 */
#define MX_PE6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PE6_Pin                              PE6
#define MX_PE6_GPIOx                            GPIOE
#define MX_PE6_PinState                         GPIO_PIN_RESET
#define MX_PE6_GPIO_PuPd                        GPIO_NOPULL
#define MX_TP2                                  PE6
#define MX_PE6_GPIO_Pin                         GPIO_PIN_6
#define MX_PE6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PC3 */
#define MX_PC3_Pin                              PC3
#define MX_PC3_GPIOx                            GPIOC
#define MX_PC3_GPIO_PuPd                        GPIO_NOPULL
#define MX_MS_INT                               PC3
#define MX_PC3_GPIO_Pin                         GPIO_PIN_3
#define MX_PC3_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

/* Pin PK0 */
#define MX_PK0_Pin                              PK0
#define MX_PK0_GPIOx                            GPIOK
#define MX_PK0_GPIO_PuPd                        GPIO_NOPULL
#define MX_DI0                                  PK0
#define MX_PK0_GPIO_Pin                         GPIO_PIN_0
#define MX_PK0_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

/* Pin PK1 */
#define MX_PK1_Pin                              PK1
#define MX_PK1_GPIOx                            GPIOK
#define MX_PK1_GPIO_PuPd                        GPIO_NOPULL
#define MX_DI1                                  PK1
#define MX_PK1_GPIO_Pin                         GPIO_PIN_1
#define MX_PK1_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

/* Pin PI14 */
#define MX_PI14_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PI14_Pin                             PI14
#define MX_PI14_GPIOx                           GPIOI
#define MX_PI14_PinState                        GPIO_PIN_RESET
#define MX_PI14_GPIO_PuPd                       GPIO_NOPULL
#define MX_LED2                                 PI14
#define MX_PI14_GPIO_Pin                        GPIO_PIN_14
#define MX_PI14_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PI6 */
#define MX_PI6_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PI6_Pin                              PI6
#define MX_PI6_GPIOx                            GPIOI
#define MX_PI6_PinState                         GPIO_PIN_RESET
#define MX_PI6_GPIO_PuPd                        GPIO_NOPULL
#define MX_NOR_nWP                              PI6
#define MX_PI6_GPIO_Pin                         GPIO_PIN_6
#define MX_PI6_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PI8 */
#define MX_PI8_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PI8_Pin                              PI8
#define MX_PI8_GPIOx                            GPIOI
#define MX_PI8_PinState                         GPIO_PIN_RESET
#define MX_PI8_GPIO_PuPd                        GPIO_NOPULL
#define MX_TP3                                  PI8
#define MX_PI8_GPIO_Pin                         GPIO_PIN_8
#define MX_PI8_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

/* Pin PI13 */
#define MX_PI13_GPIO_Speed                      GPIO_SPEED_FREQ_LOW
#define MX_PI13_Pin                             PI13
#define MX_PI13_GPIOx                           GPIOI
#define MX_PI13_PinState                        GPIO_PIN_RESET
#define MX_PI13_GPIO_PuPd                       GPIO_NOPULL
#define MX_LED1                                 PI13
#define MX_PI13_GPIO_Pin                        GPIO_PIN_13
#define MX_PI13_GPIO_ModeDefaultOutputPP        GPIO_MODE_OUTPUT_PP

/* Pin PC2 */
#define MX_PC2_Pin                              PC2
#define MX_PC2_GPIOx                            GPIOC
#define MX_PC2_GPIO_PuPd                        GPIO_NOPULL
#define MX_SD_INT                               PC2
#define MX_PC2_GPIO_Pin                         GPIO_PIN_2
#define MX_PC2_GPIO_ModeDefaultEXTI             GPIO_MODE_IT_RISING

/* Pin PA0 */
#define MX_PA0_GPIO_Speed                       GPIO_SPEED_FREQ_LOW
#define MX_PA0_Pin                              PA0
#define MX_PA0_GPIOx                            GPIOA
#define MX_PA0_PinState                         GPIO_PIN_RESET
#define MX_PA0_GPIO_PuPd                        GPIO_NOPULL
#define MX_SD_PWR_EN                            PA0
#define MX_PA0_GPIO_Pin                         GPIO_PIN_0
#define MX_PA0_GPIO_ModeDefaultOutputPP         GPIO_MODE_OUTPUT_PP

#endif  /* __MX_DEVICE_H */

